version: '3.3'

#############################################################
############################# VOLUMES #######################
#############################################################
volumes:
# MARIADB
  mariadb:
    driver: ${VOLUME_DRIVER}
# REDIS
  redis:
    driver: ${VOLUME_DRIVER}
#ELASTICSEARCH
  elasticsearch:
    driver: ${VOLUME_DRIVER}


#############################################################
############################# SERVICES ######################
#############################################################
services:
# NGINX
  nginx:
    build:
      context: ./Nginx
      dockerfile: Dockerfile
      args:
        - CONTAINER_VERSION=${NGINX_VER}
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./Source:/var/www/html
    env_file:
      - ./Nginx/.env
    depends_on:
      - php-fpm
      - mariadb
    links:
      - php-fpm

# ADMINER
  adminer:
    build:
      context: ./Adminer
      dockerfile: Dockerfile
      args:
        - CONTAINER_VERSION=${ADMINER_VER}
    ports:
      - "8080:8080"
    restart: always
    env_file:
      - ./Adminer/.env
    depends_on:
      - mariadb

# MARIADB
  mariadb:
    build:
      context: ./MariaDB
      dockerfile: Dockerfile
      args:
        - CONTAINER_VERSION=${MARIADB_VER}  
    ports:
      - "3306:3306"
    env_file:
      - ./MariaDB/.env

# PHP-FPM
  php-fpm:
    build:
      context: ./Php-fpm
      dockerfile: Dockerfile
      args:
        - CONTAINER_VERSION=${PHP_VER}
        - PHP_EXTENSION=${PHP_EXTENSION}
    env_file:
      - ./Php-fpm/.env
    volumes:
      - ./Source:/var/www/html

# REDIS
  redis:
    build:
      context: ./Redis
      dockerfile: Dockerfile
      args:
        - CONTAINER_VERSION=${REDIS_VER}
    env_file:
      - ./Redis/.env

# ELASTIC SEARCH
  elastic-search:
    build:
      context: ./Elastic-Search
      dockerfile: Dockerfile
      args:
        - CONTAINER_VERSION=${ELASTIC_SEARCH}
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    depends_on:
      - php-fpm
    env_file:
      - ./Elastic-Search/.env

# SUPERVISOR
  supervisor:
    build:
      context: ./Supervisor
      dockerfile: Dockerfile
      args:
        - CONTAINER_VERSION=${PHP_VER}
        - PHP_EXTENSION=${PHP_EXTENSION}
    env_file:
      - ./Supervisor/.env
    volumes:
      - ./Source:/var/www/html
      - ./Supervisor/config:/etc/supervisor/config
